server:
  port: 8000
spring:
  application:
    name: curso
  datasource:
    url: jdbc:postgresql://localhost:5432/curso
    username: postgres
    password: toor123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
